# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b1806653b23a8851cd8c82cd7da1006ab4a2378520d028eb70e61f31dfef71a9e70de747d9a402082ae0bae57c6b28d74bc3c56a432a8aeff1baf5b6503595e

test:
  secret_key_base: 09cbdb3c7818667c049cc9e42b6020bc0a5c327816b1f9a0a58976d6b923ccfa8bc310aac8fd401e075658ad5662393acd86ae3d64dc7a441de4e19d5ff7c75f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
